services:
  cloudcomputing-mysql-db:
    image: mysql:8.0
    container_name: cloudcomputing-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - cloudcomputing-mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

    networks:
      - cloudcomputing-network


  cloudcomputing-api:
    image: cloudcomputing-api:latest

    build:
      context: .
      dockerfile: Dockerfile

    container_name: cloudcomputing-api
    restart: unless-stopped

    depends_on:
      cloudcomputing-mysql-db:
        condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MySqlConnection: "Server=cloudcomputing-mysql-db;Port=3306;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD};"

    ports:
      - "8081:8080"

    networks:
      - cloudcomputing-network


volumes:
  cloudcomputing-mysql-data:
    name: cloudcomputing-mysql-data


networks:
  cloudcomputing-network:
    name: cloudcomputing-network
    driver: bridge