// <auto-generated />
using System;
using DotNet.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DotNet.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNet.Api.Models.CareEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("COMPLETED_DATE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("NOTES");

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("PRIORITY");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("SCHEDULED_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("NVARCHAR2(160)")
                        .HasColumnName("TITLE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("T_CP_CARE_EVENTS", (string)null);

                    b.HasData(
                        new { Id = 1, AnimalId = 1, Type = "VACCINE", Title = "Vacina V10 anual", Description = "Aplicação da vacina polivalente V10 anual obrigatória.", ScheduledDate = new DateTime(2025, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc), CompletedDate = (DateTime?)new DateTime(2025, 6, 1, 9, 30, 0, 0, DateTimeKind.Utc), Status = "COMPLETED", Priority = "HIGH", Notes = "Bolinha reagiu bem. Próxima dose em junho de 2026.", CreatedAt = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc), IsActive = true },
                        new { Id = 2, AnimalId = 2, Type = "CHECKUP", Title = "Check-up semestral Mia", Description = "Consulta de rotina com exames de sangue e urina.", ScheduledDate = new DateTime(2025, 7, 15, 14, 0, 0, 0, DateTimeKind.Utc), CompletedDate = (DateTime?)null, Status = "PENDING", Priority = "MEDIUM", Notes = "Agendar jejum de 8h antes da consulta.", CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc), IsActive = true });
                });

            modelBuilder.Entity("DotNet.Api.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("BREED");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NAME");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NICKNAME");

                    b.Property<string>("Rga")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("RGA");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SEX");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("SPECIES");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RESPONSAVEL_ID");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("T_CP_ANIMAIS", (string)null);

                    b.HasData(
                        new { Id = 1, ResponsavelId = 1, Name = "Bolinha", Nickname = "Boli", Species = "DOG", Breed = "Labrador", BirthDate = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc), Weight = 28.5m, Sex = "MALE",   Rga = "RGA-001", CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc), IsActive = true },
                        new { Id = 2, ResponsavelId = 2, Name = "Mia",     Nickname = "Miau", Species = "CAT", Breed = "Siamese",  BirthDate = new DateTime(2021, 8,  3, 0, 0, 0, 0, DateTimeKind.Utc), Weight = 4.2m,  Sex = "FEMALE", Rga = "RGA-002", CreatedAt = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc), IsActive = true });
                });

            modelBuilder.Entity("DotNet.Api.Models.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("NVARCHAR2(160)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PHONE");

                    b.HasKey("Id");

                    b.ToTable("T_CP_RESPONSAVEIS", (string)null);

                    b.HasData(
                        new { Id = 1, Name = "Ana Paula Souza",    Email = "ana.souza@email.com",   Phone = "(11) 91234-5678", Cpf = "123.456.789-00", CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc), IsActive = true },
                        new { Id = 2, Name = "Carlos Eduardo Lima", Email = "carlos.lima@email.com", Phone = "(21) 99876-5432", Cpf = "987.654.321-00", CreatedAt = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc), IsActive = true });
                });

            modelBuilder.Entity("DotNet.Api.Models.CareEvent", b =>
                {
                    b.HasOne("DotNet.Api.Models.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNet.Api.Models.Animal", b =>
                {
                    b.HasOne("DotNet.Api.Models.Responsavel", null)
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
